steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud auth activate-service-account --key-file=path/to/service-account-key.json
        gcloud app deploy app.yaml --quiet
